---
kind: DataManagerJobDefinition
kind-version: '2021.1'

name: Predicions with Jaqpot models
collection: im-jaqpot

jobs:

  jaqpot:
    name: Prediction
    description: >-
      Predicts molecular properties using Jaqpot predictive models
    version: '1.2.0'
    category: predictive models
    keywords:
    - predictive models
    - jaqpot
    - aqueous solubility
    - herg
    - ames
    - cyp2c9 inhibition
    - cyp3a4 inhibition
    - cyp2c9 substrate
    - cyp2d6 inhibition
    - lipophilicity
    - ppbr
    - hia
    - cyp2d6 substrate
    - bioavailability
    - clearance microsome
    - ld50
    - cyp3a4 substrate carbonmangels
    - caco2 wang
    - dili
    - vdss lombardo
    - clearance hepatocyte
    - half life obach
    - blood brain barrier
    - bbb
    - pgp
    image:
      name: informaticsmatters/squonk2-jaqpot
      tag: 'stable'
      project-directory: /data
      working-directory: /data
    command: >-
      /code/jaqpot.py
      {% for id in  modelID %}{{ id }} {% endfor %}
      --input '{{ inputFile }}'
      --output '{{ outputFile }}'
      {% if delimiter is defined %}--delimiter {{ delimiter }}{% endif %}
      {% if idColumn is defined %}--id-column {{ idColumn }}{% endif %}
      {% if readHeader is defined and readHeader %}--read-header{% endif %}
      {% if writeHeader is defined and writeHeader %}--write-header{% endif %}
    variables:
      order:
        options:
        - modelID
        - outputFile
        - delimiter
        - idColumn
        - readHeader
        - writeHeader
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: Molecules to predict (.sdf or .smi)
            mime-types:
            - squonk/x-smiles
            - chemical/x-daylight-smiles
            - chemical/x-mdl-sdfile
            type: file
      outputs:
        type: object
        properties:
          outputFile:
            title: Output file name (.sdf or .smi)
            mime-types:
            - chemical/x-mdl-sdfile
            - chemical/x-daylight-smiles
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}'
            type: file
      options:
        type: object
        required:
        - modelID
        - outputFile
        - delimiter
        - readHeader
        - writeHeader
        properties:
          modelID:
            title: Model IDs
            type: array
            uniqueItems: true
            items:
              title: Model ID
              type: string
              anyOf:
              - type: string
                enum:
                - solubility
                title: Aqueous solubility model
              - type: string
                enum:
                - herg
                title: hERG model
              - type: string
                enum:
                - AMES
                title: AMES model
              - type: string
                enum:
                - CYP2C9_Veith
                title: CYP2C9 inhibition model
              - type: string
                enum:
                - CYP3A4_Veith
                title: CYP3A4 inhibition model
              - type: string
                enum:
                - CYP2C9_Substrate_CarbonMangels
                title: CYP2C9 substrate model
              - type: string
                enum:
                - CYP2D6_Veith
                title: CYP2D6 inhibition model
              - type: string
                enum:
                - lipophilicity
                title: Lipophilicity model
              - type: string
                enum:
                - ppbr_az
                title: PPBR model
              - type: string
                enum:
                - hia_hou
                title: HIA model
              - type: string
                enum:
                - CYP2D6_Substrate_CarbonMangels
                title: CYP2D6 substrate model
              - type: string
                enum:
                - bioavailability_ma
                title: Bioavailability model
              - type: string
                enum:
                - clearance_microsome_az
                title: Clearance Microsome model
              - type: string
                enum:
                - ld50_zhu
                title: LD50 model
              - type: string
                enum:
                - CYP3A4_Substrate_CarbonMangels
                title: CYP3A4 Substrate CarbonMangels model
              - type: string
                enum:
                - caco2_wang
                title: CaCO2 Wang model
              - type: string
                enum:
                - dili
                title: DILI model
              - type: string
                enum:
                - vdss_lombardo
                title: VDss Lombardo model
              - type: string
                enum:
                - clearance_hepatocyte_az
                title: Clearance Hepatocyte model
              - type: string
                enum:
                - half_life+obach
                title: Half Life Obach model
              - type: string
                enum:
                - BBB
                title: Blood Brain Barrier model
              - type: string
                enum:
                - pgp
                title: PGP model
          outputFile:
            title: Output file name
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
            default: result.sdf
          delimiter:
            title: Delimiter for text formats
            type: string
            default: tab
            enum:
            - tab
            - comma
            - space
            - pipe
          idColumn:
            title: ID field (name for .sdf, zero based index for .smi)
            type: string
          readHeader:
            title: Read header line
            type: boolean
            default: true
          writeHeader:
            title: Write header line
            type: boolean
            default: true
    tests:
      # smiles-execution:
      #   inputs:
      #     inputFile: data/10.smi
      #   options:
      #     modelID:
      #     - AMES
      #     - bioavailability_ma
      #     - ld50_zhu
      #     - pgp
      #     outputFile: predictions.sdf
      #     readHeader: false
      #     writeHeader: false
      #   checks:
      #     exitCode: 0
      #     outputs:
      #     - name: predictions.sdf
      #       checks:
      #       - exists: true
      # smiles-error-execution:
      #   inputs:
      #     inputFile: data/10-error.smi
      #   options:
      #     modelID:
      #     - solubility
      #     - lipophilicity
      #     - hia_hou
      #     - herg
      #     outputFile: predictions.sdf
      #     readHeader: false
      #     writeHeader: false
      #   checks:
      #     exitCode: 0
      #     outputs:
      #     - name: predictions.sdf
      #       checks:
      #       - exists: true
      # sdf-execution:
      #   inputs:
      #     inputFile: data/candidates-10.sdf
      #   options:
      #     modelID:
      #     - CYP2C9_Veith
      #     - ppbr_az
      #     - dili
      #     - vdss_lombardo
      #     outputFile: predictions.sdf
      #     readHeader: false
      #     writeHeader: false
      #   checks:
      #     exitCode: 0
      #     outputs:
      #     - name: predictions.sdf
      #       checks:
      #       - exists: true
      # sdf-error-execution:
      #   inputs:
      #     inputFile: data/candidates-10-error.sdf
      #   options:
      #     modelID:
      #     - caco2_wang
      #     - half_life+obach
      #     - clearance_hepatocyte_az
      #     - BBB
      #     outputFile: predictions.sdf
      #     readHeader: false
      #     writeHeader: false
      #   checks:
      #     exitCode: 0
      #     outputs:
      #     - name: predictions.sdf
      #       checks:
      #       - exists: true
      smiles-result-execution:
        inputs:
          inputFile: data/1000.smi
        options:
          modelID:
          - BBB
          outputFile: predictions.smi
          readHeader: false
          writeHeader: false
        checks:
          exitCode: 0
          outputs:
          - name: predictions.smi
            checks:
            - exists: true
